### ISSUE TITLE
お題を「あいうえお」から「ぎっとはぶ」に変更

### ISSUE THREAD

**Issue by MihoEnomoto** [TakuyaFjedy/2018_github_practice#8]
「あいうえお」はもうやったので、次は「ぎっとはぶ」でやってみませんか 🤔

**Comment by MihoEnomoto** [comment]
![ミサワ](https://d20qqtosks8wga.cloudfront.net/1/7/17c29228.gif)

**Comment by kanbe392** [comment]
![寿司ゆき:spread_ikura](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/70.png)

**Comment by i48ta** [comment]
![渋い顔でバイト雑誌を見る人のイラスト（女性）](https://1.bp.blogspot.com/-yDsPHx85HbM/V7wbpO8c1vI/AAAAAAAA9P0/MCEKJSvNI-kwZZbM2KctCHmIUvvndiosACLcB/s400/job_kyuujinshi_woman_sad.png)

**Comment by i48ta** [comment]
提案が完了しました
